site_name: OneBot v12 标准
repo_name: botuniverse/onebot
repo_url: https://github.com/botuniverse/onebot
edit_uri: blob/v12-draft/v12/docs/
theme:
  name: material
  custom_dir: material
  language: zh
  logo: assets/logo-white.png
  favicon: assets/logo.png
  palette:
    primary: black
    accent: indigo
  features:
    - navigation.tabs
markdown_extensions:
  - admonition
extra:
  search:
    language: jp

nav:
  - 主页: index.md
  - 介绍: production.md
  - 生态: ecosystem.md
  - 指南:
    - 指南: specs/index.md
    - 通信: 
      - 通信概述: specs/communication/index.md
      - HTTP: specs/communication/http.md